on:
  push:
  workflow_dispatch:

env:
  DOTNET_NOLOGO: true
  VERSION: "1.1.${{ github.run_number }}"
  PACKAGES_URL: https://nuget.jcansdale-058211dd63844b65c.qaboot.net
  REPOSITORY_URL: https://jcansdale-058211dd63844b65c.qaboot.net/ghe-admin/first

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      - name: Create a .NET Core class library project
        run: dotnet new classlib
        
      - name: Add NuGetPublish.cs
        run: echo 'public class NuGetPublish { public static void SayHello() { System.Console.WriteLine("Hello from ${{ github.repository }}!"); } }' > NuGetPublish.cs

      - name: Build package
        run: dotnet pack -p:PackageVersion=${{ env.VERSION }} --output .

#      - name: Publish package
#        run: dotnet nuget push *.nupkg --api-key ${{ secrets.WRITE_PACKAGES_TOKEN }} --source ${{ env.PACKAGES_URL }}/${{ github.repository_owner }}/index.json

      - run: dotnet tool install gpr -g

      - run: gpr push *.nupkg --api-key ${{ secrets.WRITE_PACKAGES_TOKEN }} --subdomain-isolation-off --repository ${{ env.REPOSITORY_URL }}
